function data = import_STK_pose_data(filename, dataLines)
%IMPORTFILE Import data from a text file
%  TWOBODYSATELLITE1INERTIALPOSITIONVELOCITYQUATERNIONANGULARRATES =
%  IMPORTFILE(FILENAME) reads data from text file FILENAME for the
%  default selection.  Returns the data as a table.
%
%  TWOBODYSATELLITE1INERTIALPOSITIONVELOCITYQUATERNIONANGULARRATES =
%  IMPORTFILE(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  TwoBodySatellite1InertialPositionVelocityQuaternionAngularRates = importfile("C:\Users\coryt\OneDrive\Obruta Contract\STK_Ref_Scenarios\TwoBody_Satellite1_Inertial_Position_Velocity_Quaternion_Angular_Rates.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 18-Jan-2023 22:28:08

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 14);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["TimeUTCG", "xkm", "ykm", "zkm", "vxkmsec", "vykmsec", "vzkmsec", "q1vec", "q2vec", "q3vec", "q4scalar", "wxdegsec", "wydegsec", "wzdegsec"];
opts.VariableTypes = ["string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "TimeUTCG", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "TimeUTCG", "EmptyFieldRule", "auto");

% Import the data
data = readtable(filename, opts);

end